server:
  context-path: /
  display-name: ${project.build.finalName}
  port: ${SERVER_PORT}
  compression:
    enabled: true
    mime-types:
    - application/xml
    - application/json
spring:
  application:
    name: ${project.artifactId}
  pid.file: ${project.artifactId}.pid
service.url: ${SERVICE_BASEURL}/service
asiocop:
  application:
    name: asioCOP, the king of the DevOps dashboard
  roles:
    - admin
    - user
    - techsupport
